[project]
name = "bit-mutant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jhb123", email = "jhbriggs23@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "pytest>=9.1.1",
]
classifiers = [
    "Framework :: Pytest",
]

[project.entry-points."pytest11"]
bit_mutant = "bit_mutant"

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "bit-mutant-examples",
    "ruff>=0.16.10",
]

[tool.uv.workspace]
members = ["examples"]

[tool.uv.sources]
bit-mutant-examples = { workspace = true }

[tool.pytest.ini_options]
testpaths = ["test"]
pytester_example_dir = "examples/tests"
